version: "3"
services:
  jupyterlab:
    build: .
    container_name: jupyterlab
    expose:
      - "8888"
    ports:
      - "8888:8888"
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    volumes:
      - jupyter_data:/home/jovyan/work
      - $HOME/jupyterlab/jupyterlab/requirements.txt:/home/jovyan/requirements.txt:ro
      - $HOME/jupyterlab/jupyterlab/notebook-start.sh:/home/jovyan/notebook-start.sh:ro
    command: bash -c "/home/jovyan/notebook-start.sh"
volumes:
  jupyter_data:

