version: "3"

### Creates a named network with the default bridge driver
# The network is shared between restheart and mongodb only
# See: https://docs.docker.com/engine/userguide/networking/dockernetworks/
# See: https://docs.docker.com/engine/reference/commandline/network_create/
networks:
   backend:

### Create a permanent, named data volume
# This makes much easier to identify where the mongodb data is stored on host
# See: https://docs.docker.com/engine/userguide/containers/dockervolumes/#mount-a-shared-storage-volume-as-a-data-volume
volumes:
   restheart-db:

services:
   restheart-security:
      image: softinstigate/restheart-security
      container_name: restheart-security
      depends_on:
         - restheart
      networks:
         - backend
      ports:
         - "8080:8080"
      # uncomment to overwrite the configuration files
      # volumes:
      #   - ./etc/restheart-security.yml:/opt/restheart/etc/restheart-security.yml:ro
      #   - ./etc/users.yml:/opt/restheart/etc/users.yml:ro
      #   - ./etc/acl.yml:/opt/restheart/etc/acl.yml:ro

   restheart:
      image: softinstigate/restheart
      container_name: restheart
      command: ["--envFile", "etc/default.properties"]
      environment:
         MONGO_URI: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb
      depends_on:
         - mongodb
      networks:
         - backend
      # uncomment to overwrite the configuration files
      # volumes:
      #    - ./etc/restheart.yml:/opt/restheart/etc/restheart.yml:ro
      #    - ./etc/default.properties:/opt/restheart/etc/default.properties:ro

   mongodb:
      # TODO update this!
      image: mongo:4.0
      container_name: restheart-mongo
      environment:
         # must match with MONGO_URI env variable of restheart service
         MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
         MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      command: --bind_ip_all --auth
      ports:
         - "27017:27017"
      volumes:
         - restheart-db:/data/db
      networks:
         - backend

